### ISSUE TITLE
colorthief library no longer supported

### ISSUE THREAD

**Issue by SBKing103** [hoobs-org/desktop#58]
PS C:\Users\sbk10\Documents\Code\desktop> yarn global add colorthief
yarn global v1.22.11
[1/4] Resolving packages...
warning colorthief > get-pixels > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning colorthief > get-pixels > request > har-validator@5.1.5: this library is no longer supported
random for details.
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

When call init desktop application get 
PS C:\Users\sbk10\Documents\Code\desktop> yarn run lint
Debugger attached.
yarn run v1.22.11
$ vue-cli-service lint
Debugger attached.
error: Missing file extension for "colorthief/dist/color-thief" (import/extensions) at src\components\dialogs\personalize.vue:98:32:
   96 | <script>
   97 |     import ColorScheme from "color-scheme";
>  98 |     import ColorExtractor from "colorthief/dist/color-thief";
      |                                ^
   99 |
  100 |     import ColorComponent from "@/components/elements/color.vue";
  101 |     import BackdropComponent from "@/components/elements/backdrop.vue";

error: Unable to resolve path to module 'colorthief/dist/color-thief' (import/no-unresolved) at src\components\dialogs\personalize.vue:98:32:
   96 | <script>
   97 |     import ColorScheme from "color-scheme";
>  98 |     import ColorExtractor from "colorthief/dist/color-thief";
      |                                ^
   99 |
  100 |     import ColorComponent from "@/components/elements/color.vue";
  101 |     import BackdropComponent from "@/components/elements/backdrop.vue";

2 errors found.
Waiting for the debugger to disconnect...

**Comment by SBKing103** [comment]
<a href="https://github.com/lokesh/color-thief/issues/202">Facing error when &apos;npm install&apos; #202</a>

**Comment by mkellsy** [comment]
This is an eslint error not a compile error. Please install eslint globally on Windows.

Also `yarn global` is not for the current project it is the way to install modules to the system. Totally different.
